/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.
*/

function fiboEvenSum(n) {
  let fiboArray = [1,2];
  let index = 1
  while(n >= fiboArray[index]){
    let fiboNumber = fiboArray[index]+fiboArray[index-1];
    fiboArray.push(fiboNumber);
    index++;    
  }
  
  let result = 0;
  for (let i = 0; i< fiboArray.length; i++){
    if(fiboArray[i]%2 === 0){
      result += fiboArray[i]
    }
    
  }

  return result;
}